[build]
  publish = "public"
  command = "hugo --minify"

[build.environment]
  HUGO_VERSION = "0.157.0"

[context.production.environment]
  HUGO_ENV = "production"

[[redirects]]
  from = "https://tajinder.cv/*"
  to = "https://www.tajinder.cv/:splat"
  status = 301
  force = true
